import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globalCss/globals.css";
import "./globalCss/globalFonts.css";
import "./globalCss/globalAnimations.css";
import "./globalCss/globalSizes.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
